/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ChatRoomMembership } from "./ChatRoomMembership";
import { ChatRoomMembershipCountArgs } from "./ChatRoomMembershipCountArgs";
import { ChatRoomMembershipFindManyArgs } from "./ChatRoomMembershipFindManyArgs";
import { ChatRoomMembershipFindUniqueArgs } from "./ChatRoomMembershipFindUniqueArgs";
import { DeleteChatRoomMembershipArgs } from "./DeleteChatRoomMembershipArgs";
import { ChatRoomMembershipService } from "../chatRoomMembership.service";
@graphql.Resolver(() => ChatRoomMembership)
export class ChatRoomMembershipResolverBase {
  constructor(protected readonly service: ChatRoomMembershipService) {}

  async _chatRoomMembershipsMeta(
    @graphql.Args() args: ChatRoomMembershipCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ChatRoomMembership])
  async chatRoomMemberships(
    @graphql.Args() args: ChatRoomMembershipFindManyArgs
  ): Promise<ChatRoomMembership[]> {
    return this.service.chatRoomMemberships(args);
  }

  @graphql.Query(() => ChatRoomMembership, { nullable: true })
  async chatRoomMembership(
    @graphql.Args() args: ChatRoomMembershipFindUniqueArgs
  ): Promise<ChatRoomMembership | null> {
    const result = await this.service.chatRoomMembership(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ChatRoomMembership)
  async deleteChatRoomMembership(
    @graphql.Args() args: DeleteChatRoomMembershipArgs
  ): Promise<ChatRoomMembership | null> {
    try {
      return await this.service.deleteChatRoomMembership(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
