/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ChatRoomMembership as PrismaChatRoomMembership,
} from "@prisma/client";

export class ChatRoomMembershipServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ChatRoomMembershipCountArgs, "select">
  ): Promise<number> {
    return this.prisma.chatRoomMembership.count(args);
  }

  async chatRoomMemberships<T extends Prisma.ChatRoomMembershipFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatRoomMembershipFindManyArgs>
  ): Promise<PrismaChatRoomMembership[]> {
    return this.prisma.chatRoomMembership.findMany<Prisma.ChatRoomMembershipFindManyArgs>(
      args
    );
  }
  async chatRoomMembership<T extends Prisma.ChatRoomMembershipFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatRoomMembershipFindUniqueArgs>
  ): Promise<PrismaChatRoomMembership | null> {
    return this.prisma.chatRoomMembership.findUnique(args);
  }
  async createChatRoomMembership<T extends Prisma.ChatRoomMembershipCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatRoomMembershipCreateArgs>
  ): Promise<PrismaChatRoomMembership> {
    return this.prisma.chatRoomMembership.create<T>(args);
  }
  async updateChatRoomMembership<T extends Prisma.ChatRoomMembershipUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatRoomMembershipUpdateArgs>
  ): Promise<PrismaChatRoomMembership> {
    return this.prisma.chatRoomMembership.update<T>(args);
  }
  async deleteChatRoomMembership<T extends Prisma.ChatRoomMembershipDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatRoomMembershipDeleteArgs>
  ): Promise<PrismaChatRoomMembership> {
    return this.prisma.chatRoomMembership.delete(args);
  }
}
